version: 2

build:
   os: ubuntu-20.04
   tools:
      python: "3.8"  # You may specify the version you need

sphinx:
   configuration: docs/conf.py


# Build PDF & ePub
formats:
  - epub
  - pdf

python:
   install:
      - requirements: docs/requirements.txt
